# Generated by Django 5.1.7 on 2025-04-22 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RidePayout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ride_id", models.IntegerField(blank=True, null=True)),
                (
                    "ride_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cancellation_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ecp_percentage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ecp_charges",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payoutfees", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payout_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payout_total_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripetostripe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stos_id", models.CharField(blank=True, max_length=255, null=True)),
                ("stos_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stripetobank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stob_id", models.CharField(blank=True, max_length=255, null=True)),
                ("stob_date", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ride_payout",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRideTip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("txtId", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("ride_id", models.IntegerField(blank=True, null=True)),
                ("book_ride_id", models.IntegerField(blank=True, null=True)),
                ("card_id", models.IntegerField(blank=True, null=True)),
                ("tip_price", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stripe_percentage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_charges",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actual_tip_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transactionDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paymentStatus",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "failurecode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "failure_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_ride_tip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("account_holder_name", models.CharField(max_length=100)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="rides.booking",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
            },
        ),
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                        ],
                        default="card",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("PAYMENT", "Payment"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.wallet",
                    ),
                ),
            ],
        ),
    ]
