# Generated by Django 5.2.6 on 2025-09-06 08:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RidePayout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ride_id", models.IntegerField(blank=True, null=True)),
                (
                    "ride_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cancellation_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ecp_percentage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ecp_charges",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payoutfees", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payout_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payout_total_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripetostripe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stos_id", models.CharField(blank=True, max_length=255, null=True)),
                ("stos_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stripetobank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stob_id", models.CharField(blank=True, max_length=255, null=True)),
                ("stob_date", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ride_payout",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRideTip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("txtId", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("ride_id", models.IntegerField(blank=True, null=True)),
                ("book_ride_id", models.IntegerField(blank=True, null=True)),
                ("card_id", models.IntegerField(blank=True, null=True)),
                ("tip_price", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stripe_percentage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_charges",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actual_tip_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transactionDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paymentStatus",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "failurecode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "failure_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_ride_tip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("account_holder_name", models.CharField(max_length=100)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking Payment"),
                            ("tip", "Tip"),
                            ("refund", "Refund"),
                            ("penalty", "Penalty"),
                        ],
                        default="booking",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("refund_reason", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("PAYMENT", "Payment"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                        ],
                        default="card",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
