# Generated by Django 5.2.6 on 2025-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRideBook",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("txtId", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
                ("ride_id", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paymentStatus", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "user_ride_book",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("user_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20)),
                ("image", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
