# Generated by Django 5.1.4 on 2025-03-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle"
            ),
        ),
        migrations.AddField(
            model_name="carbonfootprint",
            name="ride",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="rides.ride"
            ),
        ),
        migrations.AddField(
            model_name="sosalert",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rides.ride"
            ),
        ),
        migrations.AddField(
            model_name="sosalert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
