# Generated by Django 5.1.4 on 2025-03-17 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="ride_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
