# Generated by Django 5.2.6 on 2025-09-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="rides.booking",
            ),
        ),
    ]
