# Generated by Django 5.1.4 on 2025-03-17 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rides.ride"
            ),
        ),
    ]
