# Generated by Django 5.1.7 on 2025-04-22 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("is_luxury", models.BooleanField(default=False)),
                ("country_of_origin", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Vehicle Companies",
                "db_table": "vehicle_company",
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "vehicle_type",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("color", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                ("seating_capacity", models.PositiveIntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                            ("cng", "CNG"),
                            ("lpg", "LPG"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "mileage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mileage in km/l",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "vehicle_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehiclecompany",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("registration", "Vehicle Registration"),
                            ("insurance", "Insurance"),
                            ("permit", "Permit"),
                            ("pollution", "Pollution Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_file", models.FileField(upload_to="vehicle_documents/")),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("year_from", models.IntegerField()),
                ("year_to", models.IntegerField(blank=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehiclecompany",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicletype",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_model",
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehiclemodel",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vehicles.vehicletype",
            ),
        ),
    ]
