# Generated by Django 5.1.4 on 2025-03-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=20)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("hatchback", "Hatchback"),
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("electric", "Electric Vehicle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
                ("seats_available", models.PositiveIntegerField(default=4)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
