# Generated by Django 5.1.4 on 2025-03-17 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-initiated_at"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="timestamp",
            new_name="initiated_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="INR", max_length=3, verbose_name="Currency Code"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_response",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Payment Gateway Response"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Gateway Transaction ID",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Payment Amount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="bookings.booking",
                verbose_name="Associated Booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("paypal", "PayPal"),
                    ("wallet", "Wallet"),
                    ("upi", "UPI"),
                ],
                max_length=50,
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Transaction Status",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_status"], name="bookings_pa_transac_737fcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method"], name="bookings_pa_payment_fda94c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["initiated_at"], name="bookings_pa_initiat_f94b11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("booking",), name="unique_booking_payment"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.promocode",
            ),
        ),
    ]
